f= open("ogrenciNotHesaplama.txt","w+")
print("Ogrenci not ortalama programi", file=f)
ad= input("Merhaba sayin ogrenci! Isminiz nedir? : ")
soyad= input("Soyisminiz :")
vize= int(input("Vize sinavindan aldiginiz not nedir?  :"))
final= int(input("Final sinavindan aldiginiz not nedir?  :"))
ders_takip= int(input("Lutfen ders takip bilgilerinizi paylasin? (20 dersten kac tanesine katildiniz?):"))
print(ad, file=f)
print(soyad, file=f)
print(vize, file=f)
print(final, file=f)
print(ders_takip, file=f)
print("Yil sonu puani:",(vize*30/100)+(final*50/100)+((ders_takip*5)*20/100))
print("Yil sonu puani:",(vize*30/100)+(final*50/100)+((ders_takip*5)*20/100), file=f)
f.close()

